<?php 

/**
 * @file
 * Integrates various Paytrek with Ubercart.
 *
 * You should turn on Instant Payment Notifications in your Paytrek profile and
 * set the IPN URL to http://{yoursite.com}/uc_Paytrek/ipn. See
 * https://drupal.org/node/1311198 for further information.
 */
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

use Drupal\Component\Utility\Xss;
use Drupal\uc_order\Entity\Order;
use Drupal\uc_order\OrderInterface;
use Drupal\uc_payment\Entity\PaymentMethod;
use Drupal\uc_payment\Entity\PaymentReceipt;
use Drupal\uc_payment\ExpressPaymentMethodPluginInterface;
use Drupal\uc_payment\Form\OffsitePaymentMethodForm;
use Drupal\uc_payment\OffsitePaymentMethodPluginInterface;
use Drupal\uc_payment\PaymentReceiptInterface;

/**
 * Implements hook_help().
 */
// function uc_paytrek_help($route_name, RouteMatchInterface $route_match) {
//     
// }

/**
 * Implements hook_uc_payment_gateway().
 */
// function uc_paytrek_uc_payment_gateway() {
//   	if (!\Drupal::moduleHandler()->moduleExists('uc_credit')) {
//     	drupal_set_message(t('You must <a href=":modules">enable the Credit Card module</a> to use Paytrek Payment Gateway.', [':modules' => Url::fromRoute('system.modules_list', [], ['fragment' => 'edit-modules-ubercart-payment'])->toString()]), 'warning');
// 	    return;
//   	}

//   	$gateways['paytrek_gateway'] = array(
//     	'title' => t('Paytrek Payment Gateway'),
//     	'description' => t('Process credit card payments using Website Paytrek.'),
//     	'settings' => 'uc_paytrek_settings_form',
//     	'credit' => 'uc_paytrek_charge',
//     	'credit_txn_types' => array(UC_CREDIT_AUTH_ONLY, UC_CREDIT_PRIOR_AUTH_CAPTURE, UC_CREDIT_AUTH_CAPTURE),
//   	);
// 	return $gateways;
// }

/**
 * Check that all API keys are configured.
 *
 * @return bool
 *   TRUE if all 4 keys have a value.
 */

define('QUICKPAY_VERSION', 'v10');

function uc_quickpay_form_uc_cart_checkout_form_alter(&$form, FormStateInterface $form_state) {
    $form['#attached']['library'][] = 'uc_quickpay/uc_quickpay';
    //unset($form['actions']['cancel']);
}
// function uc_quickpay_form_uc_cart_checkout_review_form_alter(&$form, FormStateInterface $form_state) {
//     global $base_url;
//     $order = $form_state->get('uc_order');
//     $plugin = \Drupal::service('plugin.manager.uc_payment.method')->createFromOrder($order);
    
//     if($plugin->getPluginId() == 'quickpay_gateway'){
//         unset($form['actions']['submit']);
//     }
// }
function _uc_quickpay_check_api_keys($configuration) {
  return $configuration['merchant_id'] &&
    $configuration['private_key'] &&
    $configuration['agreement_id'] &&
    $configuration['api_key'] &&
    $configuration['language'] &&
    $configuration['currency'];
}

/**
 * Implements hook_uc_checkout_complete()
 *
 * Saves QuickPay customer_id into the user->data object
 *
 * @param $order
 * @param $account
 */
function uc_quickpay_uc_checkout_complete($order, $account) {

  if ($order->payment_method == "credit") {
    // Pull the QuickPay customer ID from the temp storage.
    // It got there in uc_QuickPay_checkout_form_customsubmit()
    // This is only really necessary for uc_recurring
    //$QuickPay_customer_id = \Drupal::service('user.private_tempstore')->get('uc_paytrek')->get('uc_paytrek_customer_id');

    //\Drupal::getContainer('user.data')->set('uc_paytrek', $account->id(), 'uc_paytrek_customer_id', $QuickPay_customer_id);
  }
}
