# Schema for the configuration files of the uc_paytrek module.
payment_method.settings.quickpay_gateway:
    type: mapping
    label: 'QuickPay credit card configuration settings'
    mapping:
        testmode:
            type: boolean
        merchant_id:
            type: string
            label: 'Merchant ID'
        private_key:
            type: string
            label: 'Private key'
        agreement_id:
            type: string
            label: 'Agreement ID'
        api_key:
            type: string
            label: 'API key'
        language:
            type: string
            label: 'Select Language'
        currency:
            type: string
            label: 'Select Currency'
        3d_secure:
            type: string
            label: 'Select 3d_secure'
        continue_url:
            type: string
            label: 'Continue URL'
        cancel_url:
            type: string
            label: 'Cancel URL'